services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: npm install --only=production
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true 